# Generated by Django 3.0.8 on 2020-07-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_article', models.CharField(max_length=100, null=True)),
                ('particulars', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_quantity', models.IntegerField(blank=True, null=True)),
                ('issued_quantity', models.IntegerField(blank=True, null=True)),
                ('balance_quantity', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'rproduct',
            },
        ),
    ]
