# Generated by Django 3.0.8 on 2020-07-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchese',
            name='id',
        ),
        migrations.AddField(
            model_name='purchese',
            name='rproduct_id',
            field=models.IntegerField(default=-1.0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
