# Generated by Django 3.0.8 on 2020-07-18 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productlist', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_no', models.IntegerField()),
                ('fproducts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productlist.Fproduct')),
                ('rproducts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productlist.Rproduct')),
            ],
        ),
    ]
