# Generated by Django 3.0.8 on 2020-07-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imemo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='memo_no',
        ),
        migrations.AlterField(
            model_name='memo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
