# Generated by Django 3.0.8 on 2020-07-14 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productlist', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('fproduct_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productlist.Fproduct')),
            ],
        ),
    ]
